#!/usr/bin/env bash

# Subdomain configurations
declare -A subdomains
subdomains["www"]="3.83.192.251"
subdomains["lb-01"]="18.205.38.219"
subdomains["web-01"]="34.138.16.188"
subdomains["web-02"]="34.138.16.188"

# Function to query DNS and display information
runDig() {
    subdomain="$1"
    domain="$2"

    result=$(dig +short "$subdomain.$domain")
    if [ -z "$result" ]; then
        echo "The subdomain $subdomain does not exist for $domain."
    else
        record_type=$(dig +short "$subdomain.$domain" | awk '{print $2}')
        echo "The subdomain $subdomain is a $record_type record and points to $result"
    fi
}

# Check the number of arguments provided
if [ $# -eq 1 ]; then
    domain="$1"
    for subdomain in "${!subdomains[@]}"; do
        runDig "$subdomain" "$domain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    if [ -n "${subdomains[$subdomain]}" ]; then
        runDig "$subdomain" "$domain"
    else
        echo "The subdomain $subdomain is not configured for $domain."
    fi
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
